export const categories = [ 
    { value: 'Animals & Pet Supplies', label: '🐶 Animals & Pet Supplies' },
    { value: 'Apparel & Accessories', label: '👓 Apparel & Accessories' },
    { value: 'Arts & Entertainment', label: '🎨 Arts & Entertainment' },
    { value: 'Baby & Toddler', label: '👶 Baby & Toddler' },
    { value: 'Business & Industrial', label: '👔 Business & Industrial' },
    { value: 'Cameras & Optics', label: '📷 Cameras & Optics' },
    { value: 'Electronics', label: '🔋 Electronics' },
    { value: 'Food, Beverages & Tobacco', label: '🍕 Food, Beverages & Tobacco' },
    { value: 'Furniture', label: '🛌 Furniture' },
    { value: 'Hardware', label: '🔩 Hardware' },
    { value: 'Health & Beauty', label: '💅 Health & Beauty' },
    { value: 'Home & Garden', label: '🏡 Home & Garden' },
    { value: 'Luggage & Bags', label: '💼 Luggage & Bags' },
    { value: 'Mature', label: '👨‍❤️‍💋‍👨 Mature' },
    { value: 'Media', label: '📀 Media' },
    { value: 'Office Supplies', label: '📌 Office Supplies' },
    { value: 'Religious & Ceremonial', label: '🕍 Religious & Ceremonial' },
    { value: 'Software', label: '💻 Software' },
    { value: 'Sporting Goods', label: '🏐 Sporting Goods' },
    { value: 'Toys & Games', label: '🎮 Toys & Games' },
    { value: 'Vehicles & Parts', label: '🚘 Vehicles & Parts' }
];