// USER REDUCER
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// FOLLOWER REDUCER
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

// PROFILE REDUCER
export const SET_PROFILE = 'SET_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CREATE_AVATAR = 'CREATE_AVATAR';
export const DELETE_AVATAR = 'REMOVE_AVATAR';

// PROMO REDUCER
export const CREATE_PROMO = 'CREATE_PROMO';
export const UPDATE_PROMO = 'UPDATE_PROMO';
export const DELETE_PROMO = 'DELETE_PROMO';
export const LIKE_PROMO = 'LIKE_PROMO';
export const UNLIKE_PROMO = 'UNLIKE_PROMO';
export const COMMENT_PROMO = 'COMMENT_PROMO';
export const UNCOMMENT_PROMO = 'UNCOMMENT_PROMO';
export const VIEW_PROMO = 'VIEW_PROMO';
export const UPDATE_PROMO_COMMENTS = 'UPDATE_PROMO_COMMENTS';
